# data from network from other vehicles
# 话题名称: net_start_end_point_data
# 话题接口: car_interfaces/msg/NetStartEndPointInterface.msg

uint8      start1
uint8      start2
uint8      car_id
float64    time
uint8      stateid
uint8      car_mode
float32    car_speed
float32    car_angle
uint8      soc
uint8      err
uint8      errcode
float64    lon
float64    lat
float32    yaw
uint8      end1
uint8      end2
