#!/usr/bin/env sh
set -eu

if [ -n "${SSH_PASSWORD:-}" ]; then
  exec sshpass -p "${SSH_PASSWORD}" /usr/bin/scp \
    -o PubkeyAuthentication=no \
    -o PreferredAuthentications=password \
    "$@"
fi

exec /usr/bin/scp "$@"
