planner:
  ros__parameters:
    # file_name: 'Parallel_parking.txt'
    # file_name: 'observer_e_to_w.txt'
    # file_name: 'observer_w_to_e.txt'
    # file_name: 'huandao1.txt'
    file_name: apfmpc0506.txt
    # file_name: '0308NKU.txt'
    # file_name: '0308NKU_east_to_west.txt'
    # file_name: '0411observer_e_to_w.txt'
    plan_horizon: 40
    ref_speed: 2.0
    choice: 0 # 默认是0，其他参数时ref_speed无效，速度为采轨迹时开车速度（不推荐）。
    trajectory_plan: 0 # 是否选择轨迹规划，0时为路径规划，1时为轨迹规划(不推荐)。
